language: node_js
node_js: node
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAQQ7WJDGBZSG4HENK
  secret_access_key:
    secure: nI5tdyHVkbKas0iRspG3++9bUcs58MNswfrYcnlJhT+oyVSnb44paySUtWmBCRQc5iK41UglfvrurA+MkkQQ2GNXjL78ozdXLWNBw2Hm82z12PhKi15zgUJNTQhUdt3YgiOsDMS6veuPdg63aC+Lujfz/ryYpuldZx6sHColvnK+U/So147Y6kbCJmhA9FxhfIRWydQLLDb1BqOG+RJ/t/QU5Zbqx37yQN3i/lehbGKR4dwAVmsqtfVPb/fTsM5YR0dShbudBhjRRUnhkzCsXo+Oe689IgWLVoKGUMWPWjtYoj2VTGPFAb8wL8HS7971LifrlmuHAzl0I4FMmvq4UloPiP1irVuH4NOitIdq6pOZwuk3TyQPtNIODo4Ht33bcTmz4PbM8m8kkV2rb553mwPDS65ohvebSCsrIBH4kn2s/La+gJBRCc49yPj0yZ5UXLxykhy73gK8JDg/HxtAE7mgtHhwauxS+KBi1o+E0O4PFzWODDdCsyIrmjTDcdDdl5sehv2XrrsYHTY4fdcCcvHHOoIkJ17snm2la5O5Npi931rv+XOm62n8A6P4OqtRv4lqpmHhtd07RdbHVcJWhcmbZGbqjt5+iVcMtHzxGQMU4LhDHAmfIQczA7dKpqWHMpCBXFiqPCPbxjEA3ouVNxohbI+bv6Yh0KZpUY1zL5U=
  bucket: brixham-draft-updates
  local-dir: build
  on:
    repo: rahulp959/brixham-draft-updates
